language: node_js
sudo: false
node_js:
  - '12.0.0'

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  # CHECK STYLE
  - yarn run lint

  # BUILD STAGE
  - yarn run build
  - yarn run build:integration
  - yarn run build:integration:ssr

  # TEST STAGE
  - yarn run test:ci
  - yarn run test:ci:integration
  - yarn run test:ci:integration:ssr

  # INTEGRATION TEST
  - yarn run integration:ng5

  # INTEGRATION TEST
  - yarn run test:types

  # CHECK BUNDLE SIZE
  - yarn run bundlesize
